export const actionTypes = {
  REGISTER_USER: "REGISTER_USER",
  USERS_ERROR: "USERS_ERROR",

  LOGIN_USER: "LOGIN_USER",
  LOGIN_ERROR: "LOGIN_ERROR",

  LOGOUT_USER: "LOGOUT_USER",
  LOGOUT_ERROR: "LOGOUT_ERROR",

  GET_USER: "GET_USER",
  GET_USER_ERROR: "GET_USER_ERROR",

  SET_USER: "SET_USER",
  SET_USER_ERROR: "SET_USER_ERROR",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_ERROR: "DELETE_USER_ERROR",

  GET_USERS: "GET_USERS",
  GET_USERS_ERROR: "GET_USERS_ERROR",

  SET_CUSTOMERS: "SET_CUSTOMERS",
  SET_CUSTOMERS_ERROR: "SET_CUSTOMERS_ERROR",

  GET_CUSTOMERS: "GET_CUSTOMERS",
  GET_CUSTOMERS_ERROR: "GET_CUSTOMERS_ERROR",

  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_ERROR: "GET_USER_BY_ID_ERROR",

  GET_USER_BY_EMAIL: "GET_USER_BY_EMAIL",
  GET_USER_BY_EMAIL_ERROR: "GET_USER_BY_EMAIL_ERROR",

  GET_USER_BY_USERNAME: "GET_USER_BY_USERNAME",
  GET_USER_BY_USERNAME_ERROR: "GET_USER_BY_USERNAME_ERROR",

  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",

  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SELECTED_PRODUCT_ERROR: "SELECTED_PRODUCT_ERROR",

  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT_ERROR: "REMOVE_SELECTED_PRODUCT_ERROR",

  GET_TYPE:'GET_TYPE',
  GET_CATEGORY:'GET_CATEGORY',

  GET_ORDERS:'GET_ORDERS',
};
